# Generated by Django 3.0.4 on 2020-03-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gonderi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.TextField()),
                ('resim', models.ImageField(upload_to='resimler/')),
            ],
        ),
    ]
