# Generated by Django 3.0.4 on 2020-03-26 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sorular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_cumlesi', models.CharField(max_length=200)),
                ('yayim_zaman', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Secenek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_metin', models.CharField(max_length=200)),
                ('cevap', models.IntegerField(default=0)),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketler.Sorular')),
            ],
        ),
    ]
