# Generated by Django 3.0.4 on 2020-03-26 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anketler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorular',
            name='kayit_zaman',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 14, 1, 27, 206117, tzinfo=utc)),
        ),
    ]
