# Generated by Django 3.0.4 on 2020-03-26 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anketler', '0002_sorular_kayit_zaman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorular',
            name='kayit_zaman',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
