# Generated by Django 3.0.4 on 2020-03-27 21:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('ozet', models.TextField(max_length=1000)),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
            ],
        ),
        migrations.CreateModel(
            name='Tur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(help_text='Bir kitap türü giriniz (Duygusal Romantik gibi)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100)),
                ('soyadi', models.CharField(max_length=100)),
                ('dogum_tarihi', models.DateField(blank=True, null=True)),
                ('olum_tarihi', models.DateField(blank=True, null=True, verbose_name='Öldü')),
            ],
            options={
                'ordering': ['soyadi', 'adi'],
            },
        ),
        migrations.CreateModel(
            name='KitapGiris',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('imyazi', models.CharField(max_length=200)),
                ('geri_donus', models.DateField(blank=True, null=True)),
                ('durum', models.CharField(blank=True, choices=[('G', 'Rafta'), ('U', 'Ulaşılabilir'), ('K', 'Kirada'), ('R', 'Rezerve')], default='G', max_length=1)),
                ('kitap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.Kitap')),
            ],
            options={
                'ordering': ['geri_donus'],
            },
        ),
        migrations.AddField(
            model_name='kitap',
            name='tur',
            field=models.ManyToManyField(to='katalog.Tur'),
        ),
        migrations.AddField(
            model_name='kitap',
            name='yazar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.Yazar'),
        ),
    ]
